name: Build and Deploy

on:
  push:
    branches:
      - development  # change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Build solution
      run: dotnet build src/Presentation/Nop.Web/Nop.Web.csproj --configuration Release

    - name: Publish
      run: dotnet publish src/Presentation/Nop.Web/Nop.Web.csproj --configuration Release --output ./publish

    - name: Zip publish folder
      run: zip -r ../publish.zip .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dev-be-babysaffron'
        package: src/Presentation/Nop.Web/publish.zip
        slot-name: production  # optionally, specify deployment slot name
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_85EF86EBFDE04F478951ABEEEDEE18B7}}
